# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: rtlamr
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - dragonfly
      - freebsd
      - linux
      - netbsd
      - openbsd
      - plan9
      - solaris
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mips64
      - mips64le
      - mipsle
      - ppc64
      - ppc64le
      - s390x
    goarm:
      - 7
    ldflags:
      - -s -w -X main.buildTag={{.Version}} -X main.buildDate={{ time "2006-01-02" }} -X main.commitHash={{.Commit}}
archive:
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: 'rtlamr-{{.Commit}}'
changelog:
  sort: asc
sign:
  args: ["-u", "C0BB0C3597F9BCFE", "--output", "${signature}.asc", "--armor", "--detach-sign", "${artifact}"]
  artifacts: checksum
release:
  disable: true
  github:
    owner: bemasher
    name: rtlamr
  draft: true